apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../observability
  - namespace.yml

namespace: dev

# patches:
#   - path: frontend.yml
#   - path: backend.yml
