creation_rules:
  - path_regex: ".*\\.ya?ml$" # encrypt every .yaml file found
    unencrypted_regex: "^(apiVersion|metadata|kind|type)$" # do not encrypt this values
    kms: arn:aws:kms:ap-southeast-2:665303624691:alias/fileops-dev
