apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-db-secrets
      containers:
        - image: 665303624691.dkr.ecr.ap-southeast-2.amazonaws.com/fileops-backend:986c0c5f712eaf42c46af01e404c9d80c71a9fff
          name: fileops-backend
          volumeMounts:
            - name: secrets-store-inline
              mountPath: /mnt/secrets-store
              readOnly: true
            - name: db-ca-cert-config
              mountPath: /db
              readOnly: true
          env:
            - name: PORT
              value: "8080"
            # TODO: Change this after certs are set up
            - name: CORS_ORIGIN
              value: http://k8s-dev-webalb-1670f04e40-722343320.ap-southeast-2.elb.amazonaws.com
            - name: AWS_REGION
              value: ap-southeast-2
            - name: S3_BUCKET_NAME
              value: fileops-dev
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-access-key
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-access-key
                  key: AWS_SECRET_ACCESS_KEY
            - name: DB_HOST
              value: fileops-postgres.cry0yoiwuh41.ap-southeast-2.rds.amazonaws.com
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: fileopsdb
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: SSL_ROOT_CERT
              value: /db/global-bundle.pem
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: db-secrets
        - name: db-ca-cert-config
          configMap:
            name: db-ca-cert
            items:
              - key: global-bundle.pem
                path: global-bundle.pem
