apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-secrets
spec:
  provider: aws
  secretObjects:
    - secretName: db-secrets
      type: Opaque
      data:
        - objectName: username
          key: username
        - objectName: password
          key: password
  parameters:
    region: ap-southeast-2
    objects: |
      - objectName: rds!db-a3907108-7a15-4db1-824b-a6802bbc4a4c
        objectType: secretsmanager
        jmesPath:
          - path: username
            objectAlias: username
          - path: password
            objectAlias: password
