apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-secrets
spec:
  provider: aws
  secretObjects:
    - secretName: db-secrets
      type: Opaque
      data:
        - objectName: username
          key: username
        - objectName: password
          key: password
  parameters:
    region: ap-southeast-2
    objects: |
      - objectName: rds!db-2ee3288d-5bab-4e40-a6e4-ae56b28a6c35
        objectType: secretsmanager
        jmesPath:
          - path: username
            objectAlias: username
          - path: password
            objectAlias: password
