apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "rds!db-2d94edbb-aee4-499c-a833-a4224dd19a47"
        objectType: "secretsmanager"
