apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: 665303624691.dkr.ecr.ap-southeast-2.amazonaws.com/fileops-frontend:723d3d794b7878fd576a518e649369102230c3bf
          name: fileops-frontend
          resources:
            requests:
              cpu: 200m
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
