apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: backend-scaledobject
spec:
  scaleTargetRef:
    # The deployment name
    name: backend
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-server.prometheus.svc.cluster.local
        # Each replica should handle about this much of estimated wait time
        threshold: "1200"
        query: |
          max(
            fileops_estimated_last_job_wait_seconds{
              namespace="dev",
              service="backend-svc"
            }
          )
