apiVersion: v1
kind: Secret
metadata:
    name: aws-access-key
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:CZUvDKaFFJ7nsIUVW6cOhpCkue0=,iv:wFnCQJEhuNA1M5yVU6HCrkmx2f/p7FGM9BGeOzwkOBc=,tag:E17MQtHQJz71h8/pIxgqSA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Gb1mhwK4MPTXUnGq2FHQ0jeDs1aJHV5fTOnkq1OjLSCoA1Dy0UtMdg==,iv:pu/jhFv572AgqXDKcBMufmAjiCGJOLBWN6ztBp9DvrM=,tag:+R9TxXo8SaqPqbM6kDHH4w==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    kms:
        - arn: arn:aws:kms:ap-southeast-2:665303624691:key/ddb3f1ef-5194-4fa2-b4e1-e914831a249b
          aws_profile: ""
          created_at: "2026-05-21T12:37:54Z"
          enc: AQICAHjiJNsl6KgE2M/vZ26j6K1MI4vd+sXguMWi/HXxa9VzBwH/xH3OiMEUseG7EsSrYHTKAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMpyEEphmk0jcSFWTTAgEQgDs4//XMlobv3VL0/zZrX96RY2NW2vRhUgXQnRH/o2uA8XCtQIVY2NCfHTAGNNjthOMaZM08DW4ujsTlPg==
    lastmodified: "2026-05-21T12:38:13Z"
    mac: ENC[AES256_GCM,data:2ZOesayYfKdweVo0xHeQE4QkNZTl51dCzeIW2vN4MLpPsD+b2JMz6EZai4ivF7TzTqGG81qicntfrKHkvlMaIeEKyFDS9o1DgoWnttebgywkbBph3rfrfNRD2dcf/3+Rhq8A+xQzinuJDnsbSyuo9jeaulV7EHQ4GPQxwXRtSz0=,iv:JVJBJosFq1DPQXwMeUxAP6cdyvLqtuDyEofTu/t2aQI=,tag:WN3f06oZF2LOZPDwXAytCA==,type:str]
    version: 3.13.1
