apiVersion: v1
kind: Secret
metadata:
    name: aws-access-key
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:aTmO0nuY/XraCuTE/XXxiy1QJH0=,iv:wFnCQJEhuNA1M5yVU6HCrkmx2f/p7FGM9BGeOzwkOBc=,tag:U/UshnNLe1ZgM4OjdXXMlA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2MP7hId9ajIXpDwJd7MCVGA1AAMHkAUSJPrwq7qeCbVrtblKeHzBtQ==,iv:pu/jhFv572AgqXDKcBMufmAjiCGJOLBWN6ztBp9DvrM=,tag:Hu3atl7NoD3DqTSYk0RP1g==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    kms:
        - arn: arn:aws:kms:ap-southeast-2:665303624691:key/ddb3f1ef-5194-4fa2-b4e1-e914831a249b
          aws_profile: ""
          created_at: "2026-05-19T08:26:47Z"
          enc: AQICAHjiJNsl6KgE2M/vZ26j6K1MI4vd+sXguMWi/HXxa9VzBwFnIVnRbVZX7dBT3ACsvEDOAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM7PSRBXsK/ygihJS3AgEQgDt02SEzfzq57rOUSTWk9TWpydUydD6IOK84luImJ/ntvQXMHJppSDNRsCNYu0Rzbf/uW61ychFyfsFQQg==
    lastmodified: "2026-05-19T08:26:49Z"
    mac: ENC[AES256_GCM,data:uk5mGv3PrmJbheEI6CPAtG8qqggksTWwOgmpkfZnbWva6hZwIbwOM8PtXLEKBUN60q7ScZx3nYM3oyVRcvL2pyLPWmETV5D0m+rcEUcGn/Pp3GKB9CkuPdcykeIkQzqnSvDtd7UlGgBZyCuAZinT4HnGOiaKATwsZFHaY6+eGDc=,iv:ESd0O03+v9qyVUFW6wbKJlJ0rVgXs42AdwDLfUJSs6w=,tag:6KdCW87Qzmu6a/MBGyGY4w==,type:str]
    version: 3.13.1
