apiVersion: v1
kind: Secret
metadata:
    name: aws-access-key
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:EHvr3xIMbBKOZbzAu1r8KAtr35g=,iv:wFnCQJEhuNA1M5yVU6HCrkmx2f/p7FGM9BGeOzwkOBc=,tag:Ap7DZU4XXlu5wQTcuRz9Gw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:hbDgj6UNEsV1YH8+npstYJWTcJ8xeExzMPet/HKF6XMPzG365WblMg==,iv:pu/jhFv572AgqXDKcBMufmAjiCGJOLBWN6ztBp9DvrM=,tag:5/6hvaDCC9Rzm5SIjHHI7g==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    kms:
        - arn: arn:aws:kms:ap-southeast-2:665303624691:alias/fileops-dev
          aws_profile: ""
          created_at: "2026-05-21T10:49:00Z"
          enc: AQICAHjiJNsl6KgE2M/vZ26j6K1MI4vd+sXguMWi/HXxa9VzBwGWiFDDQ9+kkHqp/JxgHXzGAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMZnMNllIOGQZGGN32AgEQgDshWCASYQtOhTFLGqYANDohNxw2HZYEAodfN5qJh1v4FTC0YG2WVXBMuXnW0MntrJOrT7/KfggUCQ1ohg==
    lastmodified: "2026-05-21T10:50:05Z"
    mac: ENC[AES256_GCM,data:ldm+XTp4dwC6e+A614NthEvnDG5U0QSbRtpg5MTdz2H3Oa7Odv2pGbUNSz+22gnQoKrWFXWxPLpvvKSKZ6lvW1Ro6QOm+fxIXY9x85n06LT5IHPONDFPcHhPlY8m33fIjQ8ic0BULWDEXDiNMcCb+g4WtWLVaMNaIKCXcBPWf44=,iv:QySH6ICLpANPofyEYTv/1497up0tW4DLpwXo9pQXVng=,tag:DVYheWXN4srv6wMwr+UmUA==,type:str]
    version: 3.13.1
